---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: hello
  namespace: flux-system
spec:
  ref:
    tag: deploy/hello/v1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: hello
  namespace: flux-system
spec:
  path: ./apps/hello/overlays/clusters/dankn/namespaces/dankn
