---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization

metadata:
  name: hello
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./apps/hello/overlays/clusters/<the-cluster>/namespaces/<the-namespace>
  prune: true
  sourceRef:
    kind: GitRepository
    name: hello
  validation: client
