---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dankn-flux-live
  namespace: flux
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux
  url: ssh://git@github.com/DanSipola/hello
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dankn-flux-live
  namespace: flux
spec:
  interval: 10m0s
  path: ./live/clusters/dankn
  prune: true
  sourceRef:
    kind: GitRepository
    name: dankn-flux-live
  validation: client
