apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: monopole/hello
  newTag: latest
namePrefix: staging-
commonLabels:
  variant: staging
resources:
- ../../../base

patchesStrategicMerge:
- configmap.yaml
