apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: core
resources:
- ../../../../apps/hello/base/

components:
- ../../../components/azure/aadpodidentity/

patchesStrategicMerge:
- configmap.yaml
- deployment.yaml
