apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: monopole/hello
  newTag: v2.0

namePrefix: production-
commonLabels:
  variant: production
resources:
- ../../../base

patchesStrategicMerge:
- configmap.yaml
