apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

resources:
  - ../../../../base

patchesStrategicMerge:
  - patch.yaml

patches:
- path: trackmain.yaml
  target:
    kind: GitRepository
